name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$GITHUB_REF_NAME .

      - name: push
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$GITHUB_REF_NAME
